[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "oquarekg_package"
version = "0.1.0"
description = "OQuaRE-KG is a quality evaluation framework for assessing knowledge graphs, based on OQuaRE"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  {name = "Belen Juanes Cortes"}
]

dependencies = [
    "rdflib",
    "pandas"
]


[project.scripts]
oquarekg-evaluate = "oquarekg.evaluation:main"
oquarekg-scores = "oquarekg.scoring:main"
oquarekg = "oquarekg:main"